name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yashwanthkumar1999/azure-be-ga:latest
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
         host: 20.166.35.113
         username: demo
         password: ${{ secrets.VM_PASSWORD }} 
         port: 22
         script: |
          # Commands to execute on the VM after SSH connection
          sudo docker stop my-container || true
          sudo docker rm my-container || true
          sudo docker run -d --name my-container -p 8080:80 yashwanthkumar1999/azure-be-ga:latest
