name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yashwanthkumar1999/azure-be-ga:latest
      -
        name: Publish to Azure VM
        uses: Azure/docker-login@v1
        with:
          login-server: 40.87.66.250
          username: demo
          password: ${{ secrets.VM_PASSWORD }}
      -
        name: Deploy to Tomcat
        run: |
          docker pull yashwanthkumar1999/azure-be-ga:latest
          docker run -d -p 8080:8080 --name myapp yashwanthkumar1999/azure-be-ga:latest
